// src/pages/Schedule.tsx
import React, { useState, useEffect } from 'react';
import fetch from 'isomorphic-unfetch';
import { Page, Testimonial, Class } from '../components';

export const Schedule = () => {
  const [classes, setClasses] = useState();

  useEffect(() => {
    getClasses.then(json => setClasses(sloppyParse(json)));
  }, []);

  // useEffect(() => {
  //   setTimeout(
  //     () => getClasses.then(json => setClasses(sloppyParse(json))),
  //     1000,
  //   );
  // });

  return (
    <Page title="Schedule">
      <Testimonial source="Laura">
        Our community has gravitated to Holly’s sessions not only
        because she knows her craft really well, but more so the time
        she takes to listen to people’s pain. Anyone can call
        themselves a yoga instructor, but Holly's talent is natural.
        She is truly a gift.
      </Testimonial>

      <img src="/static/5.jpg" />

      {classes &&
        classes.map((c: any, i: number) => (
          <Class
            key={i}
            day={c.day}
            description={c.description}
            end={c.end}
            href={c.link}
            level={c.level}
            location={c.location}
            name={c.name}
            start={c.start}
          />
        ))}
    </Page>
  );
};

function sloppyParse(entries: any[]) {
  return entries.map(entry => {
    const data = entry.content.$t
      .split(/(?:[a-z]{3,}: )/g)
      .map((str: string) =>
        str.slice(-2) === ', ' ? str.slice(0, -2) : str,
      );

    return {
      day: data[1],
      location: data[2],
      name: data[3],
      start: data[4],
      end: data[5],
      description: data[6],
      level: data[7],
      link: (data[9] && 'https://' + data[9]) || null,
    };
  });
}

const db =
  'https://spreadsheets.google.com/feeds/list/1Gk3csWwFL6jYr-MzY0kw6LR8DCju_7ShoeiBBQzB7Yc/od6/public/basic?alt=json';

const getClasses = fetch(db).then(data =>
  data.json().then(json => json.feed.entry),
);

// src/app/pages/schedule/schedule.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-schedule',
  templateUrl: './schedule.component.html',
  styleUrls: ['./schedule.component.scss']
})
export class ScheduleComponent implements OnInit {

  constructor() {
    console.log();
  }

  ngOnInit() {
  }

}

<div class="testimonial">
  <h2>Our community has gravitated to Holly’s sessions not only because she knows her craft really well, but more so the time she takes to listen to people’s pain. Anyone can call themselves a yoga instructor, but Holly's talent is natural. She is truly a gift.</h2>
  <span class="source">Laura</span>
</div>

<img src="/assets/5.jpg">

<div class="day">
  <h2>Tuesday</h2>
  <time>7:15pm - 8:30pm</time>
  <div class="level">Open to All</div>

  <div class="location">Physical Equalibrium</div>
  <span class="description">This 75 minute flow and restore class is open to all! Join me after your workday to unwind and rejuvenate. Please see the Physical Equilibrium website for payment details.</span>

  <a target="_blank" href="https://clients.mindbodyonline.com/classic/mainclass?studioid=18003">learn more or register &raquo;</a>
</div>

<div class="day">
  <h2>Tuesday</h2>
  <time>12:00pm - 1:15pm</time>
  <div class="level">Open to All</div>

  <div class="location">Physical Equalibrium</div>
  <span class="description">This 75 minute flow and restore class is open to all! Join me after your workday to unwind and rejuvenate. Please see the Physical Equilibrium website for payment details.</span>

  <a target="_blank" href="https://clients.mindbodyonline.com/classic/mainclass?studioid=18003">learn more or register &raquo;</a>
</div>

<div class="day">
  <h2>Wednesday</h2>
  <time>7:30pm - 8:30pm</time>
  <div class="level">Open to All</div>

  <div class="location">Church on the Hill</div>
  <span class="description">Free yoga for all shapes, sizes, ages, and skill levels. A limited number of mats will be available. No sign up necessary.</span>

  <a target="_blank" href="http://www.churchonthehill.org/events/">learn more or register &raquo;</a>
</div>

<div class="day">
  <h2>Thursday</h2>
  <time>10:00am - 11:30am</time>
  <div class="level">Open to All</div>

  <div class="location">Steps on Broadway</div>
  <span class="description">Rooted in a safe, alignment-based, breath-focused, mindful-flow style and are appropriate for anybody interested in cultivating sustainable pathways of the body and mind. See their website for payment information and class packages.</span>

  <a target="_blank" href="https://www.stepsnyc.com/faculty/bio/Holly-Ledbetter/">learn more or register &raquo;</a>
</div>

<div class="day">
  <h2>Friday</h2>
  <time>1:30pm - 2:45pm</time>
  <div class="level">Open to All</div>

  <div class="location">Physical Equalibrium</div>
  <span class="description">This 75 minute flow and restore class is open to all! Join me after your workday to unwind and rejuvenate. Please see the Physical Equilibrium website for payment details.</span>

  <a target="_blank" href="https://clients.mindbodyonline.com/classic/mainclass?studioid=18003">learn more or register &raquo;</a>
</div>
